### ISSUE TITLE
support laravel 10

### ISSUE THREAD

**Issue by hooman-mirghasemi** [apichef/laravel-obfuscate#6]
please add laravel 10 support :
"laravel/framework": "^8.0|^9.0|^10.0",

**Comment by hooman-mirghasemi** [comment]
"illuminate/database": "^8.0|^9.0|^10.0",
        "illuminate/support": "^8.0|^9.0|^10.0",

**Comment by craigrileyuk** [comment]
If anyone needs an open-source alternative for this that's Laravel 10 compatible:

https://packagist.org/packages/evo-mark/laravel-id-obfuscator

**Comment by nimnaherath** [comment]
Fixed #13
